import { CoreProperties, Dependency } from "@schemastore/package"
import { Rawable } from "."
import * as os from 'os'
import { CliConfig } from "src"

export type PackageJson = CoreProperties & Rawable

// Default packagejson
const packageJson: PackageJson = {
    version: '1.0.0',
    description: 'Demo generated by B6E8 CLI',
    keywords: ['browser-extension', 'chrome', 'firefox', 'edge'],
    author: os.userInfo().username || 'unkown',
    scripts: {
        "dev": "webpack --mode=development --config=webpack/webpack.dev.js --watch",
        "build": "webpack --mode=production --config=webpack/webpack.prod.js",
        "test": "jest",
        "testc": "jest --converage"
    },
    toRaw() {
        return JSON.stringify(this, null, 4)
    }
}

const dependencies: Dependency = {}

const devDependencies: Dependency = {
    "@types/chrome": "^0.0.142",
    "@types/jest": "^26.0.23",
    "webpack": "^5.37.1",
    "webpack-cli": "^4.7.0",
    "ts-jest": "^27.0.0",
    "ts-loader": "^9.2.2",
    "sass": "^1.34.0",
    "sass-loader": "^11.1.1",
    "style-loader": "^2.0.0",
    "css-loader": "^5.2.6",
    "typescript": "^4.2.4",
    "eslint": "^7.27.0",
    "copy-webpack-plugin": "^9.0.0",
    "filemanager-webpack-plugin": "^5.0.0",
    "generate-json-webpack-plugin": "^2.0.0",
}

export default (config: CliConfig) => {
    packageJson.name = config.name
    packageJson.license = config.license
    if (config.vue === 3) {
        dependencies["vue"] = "^3.0.11"
        dependencies["vue-router"] = "^4.0.6"
    }

    packageJson.dependencies = dependencies
    packageJson.devDependencies = devDependencies
    return packageJson
}